dockerfile+architect file copying update
architect-templates/springboot pull request #4
Opened 2023-01-26 19:36 UTC by ryan-cahill

## Changes
* Copying just the source and `pom-xml` to the container
* Updating debug volume to just mount the source
* Renaming Dockerfile

2023-03-20 13:30 UTC, TylerAldrich commented on README.md
> +architect deploy springboot:latest --account <account-name> --environment my-first-environment
Related to Michael's comment here - https://architect-io.slack.com/archives/C02A25LFWHH/p1679003232674869?thread_ts=1678979892.057029&cid=C02A25LFWHH - he's going to check with Zach + Mandy but I believe this should be `architect deploy --account <account-name> --environment my-first-environment ./architect.yml` because we never mention elsewhere how to register the component

2023-03-20 13:33 UTC, TylerAldrich commented on src/main/java/com/architect/springboot/controller/MovieRatingController.java
> +  @GetMapping("/movierating")
Something we should also check in with Zach about and I think was a little unclear in the requirements - there's a line in the readme:
```
Give it a try! Search inside your project for “Movie Ratings” and change this string to “Pizza Ratings."
```
and because of that in the Go/NodeJS project I updated the language of the code to be generic and use an "Item" table with "Rating" and "Name" and used that in the endpoint too (https://github.com/architect-templates/go/pull/2/files#diff-5efd4fd9208dae00a924b10a8f6f9807c78e5522dbe087646a42ef726c493f5eL26)

We should check in with Zach and see if that's needed or not, I don't exactly know how uniform they want the internals of the projects to be vs. just externally looking/feeling similar

2023-03-21 03:51 UTC, mtgoncalves1 requested changes

2023-03-21 03:51 UTC, mtgoncalves1 commented on README.md
> +%architect environments:create my-first-environment
Add a space between % architect

2023-03-21 03:51 UTC, mtgoncalves1 commented on README.md
> +%architect init
Add a space between % architect

2023-03-21 03:51 UTC, mtgoncalves1 commented on README.md
> +architect deploy springboot:latest --account <account-name> --environment my-first-environment
I can confirm that `architect deploy springboot:latest --account <account-name> --environment my-first-environment` did not work but `architect deploy --account <account-name> --environment my-first-environment` worked

2023-03-21 13:33 UTC, ryan-cahill commented on src/main/java/com/architect/springboot/controller/MovieRatingController.java
> +  @GetMapping("/movierating")
@Zach-at-Arch how much do you care about this? I left this as-is since this uses movie ratings to start with and the user might never actually change it, but I could go either way

2023-03-21 19:13 UTC, Zach-at-Arch commented on src/main/java/com/architect/springboot/controller/MovieRatingController.java
> +  @GetMapping("/movierating")
The biggest thing I worry about is UX, so how the project feels when booting up and the actual UI portion as well.

I am not worried as much about what's going on under the hood, just as long as it doesn't add additional maintenance burden.

2023-03-21 19:58 UTC, TylerAldrich commented on src/main/java/com/architect/springboot/controller/MovieRatingController.java
> +  @GetMapping("/movierating")
Cool, sounds like this is good to go then 👍

2023-03-21 19:58 UTC, merged